[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mini-hack"
version = "2023.0.1"
readme = "README.md"
description = "Projects from the PlainBagel Mini-Hack 2023"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "streamlit",
    "python-dotenv",
    "pandas",
    "tweepy",
    "watchdog"
]

[project.optional-dependencies]
dev = [
    "black[d]>=23.3.0",
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.0.276",
    "mypy>=1.4.1",
    "watchdog>=3.0.0",
    "httpx>=0.24.1"
]

[tool.hatch.build]
packages = [
    "src/mini_hack"
]
#only-packages = true
skip-excluded-dirs = true
exclude = [
    "/.github",
    "/.idea",
    ".gitignore",
    "src/mini_hack/team_03",
]
artifacts = [
    "*.pkl",
    "*.so",
    "*.dll",
]
#macos-max-compat = false

#[tool.hatch.build.targets.wheel.hooks.mypyc]
#dependencies = ["hatch-mypyc"]
#include=["src/playground/placeholder.py"]


[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories in the root of the project.
(
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.mypy]
disallow_any_unimported = true
disallow_untyped_defs = true
strict_equality = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
check_untyped_defs = true
show_error_codes = true
exclude = [
    'venv',
    '_pb2.py$', # exclude autogenerated Protocol Buffer files anywhere in the project
    '_pb2_grpc.py$', # exclude autogenerated Protocol Buffer files anywhere in the project
    'saved',
    'wandb',
]


[tool.ruff]
line-length = 120
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "PLE", # pylint errors
    "NPY", # numpy
    "PTH", # pathlib
    "SIM", # flakes8-simplify
    "N", # pep8-naming

]
ignore = [
    "E501", # line too long, handled by black
    "SIM116", # disable Use a dictionary instead of consecutive `if` statements
    #    "B008",  # do not perform function calls in argument defaults
    "C901", # too complex
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401", "I"]  # imported but unused

[tool.ruff.isort]
lines-after-imports = 2
combine-as-imports = true


